# /* Copyright (C) 2022 Cloud Data Consultants Inc. - All Rights Reserved
# *
# * You may not copy, reproduce, distribute, transmit, modify, create derivative works, 
# * or in any other way exploit any part of copyrighted material without permission.
# * 
# */

config-version: 2

name: 'cdc_dbt_utils'
version: '0.3.1'


require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  dw_util:
    materialized: table
