-- this select statement is for testing and development purposes only
-- it was a way to verfy that claude code, and claude the app did not randomly rename columns.
-- note initially we had them all together and prefixed with calendar_ and trade_ but that was unwieldy
select
    d.date_key
    , d.calendar_full_dt
    , d.full_dt
    , d.calendar_date_last_year_key
    , d.trade_date_last_year_key
    , d.calendar_day_of_week_num
    , d.iso_day_of_week_num
    , d.calendar_day_of_month_num
    , d.calendar_day_of_quarter_num
    , d.calendar_day_of_year_num
    , d.trade_day_of_year_num
    , d.calendar_day_overall_num
    , d.calendar_day_nm
    , d.calendar_day_abbr
    , d.calendar_day_suffix_txt
    , d.calendar_epoch_num
    , d.calendar_weekday_flg
    , d.calendar_last_day_of_week_flg
    , d.calendar_first_day_of_month_flg
    , d.calendar_last_day_of_month_flg
    , d.calendar_last_day_of_quarter_flg
    , d.calendar_last_day_of_year_flg
    , d.calendar_week_num
    , d.trade_week_num
    , d.calendar_week_of_year_num
    , d.trade_week_of_year_num
    , d.calendar_week_of_month_num
    , d.trade_week_of_month_445_num
    , d.trade_week_of_month_454_num
    , d.trade_week_of_month_544_num
    , d.calendar_week_of_quarter_num
    , d.trade_week_of_quarter_num
    , d.calendar_week_overall_num
    , d.trade_week_overall_num
    , d.calendar_week_start_dt
    , d.trade_week_start_dt
    , d.calendar_week_start_key
    , d.trade_week_start_key
    , d.calendar_week_end_dt
    , d.trade_week_end_dt
    , d.calendar_week_end_key
    , d.trade_week_end_key
    , d.calendar_month_num
    , d.trade_month_445_num
    , d.trade_month_454_num
    , d.trade_month_544_num
    , d.calendar_month_nm
    , d.trade_month_445_nm
    , d.trade_month_454_nm
    , d.trade_month_544_nm
    , d.calendar_month_abbr
    , d.trade_month_abbr
    , d.calendar_month_in_quarter_num
    , d.calendar_month_overall_num
    , d.trade_month_overall_num
    , d.calendar_yearmonth_num
    , d.trade_yearmonth_num
    , d.calendar_month_start_dt
    , d.trade_month_445_start_dt
    , d.trade_month_454_start_dt
    , d.trade_month_544_start_dt
    , d.calendar_month_start_key
    , d.trade_month_445_start_key
    , d.trade_month_454_start_key
    , d.trade_month_544_start_key
    , d.calendar_month_end_dt
    , d.trade_month_445_end_dt
    , d.trade_month_454_end_dt
    , d.trade_month_544_end_dt
    , d.calendar_month_end_key
    , d.trade_month_445_end_key
    , d.trade_month_454_end_key
    , d.trade_month_544_end_key
    , d.calendar_quarter_num
    , d.trade_quarter_num
    , d.calendar_quarter_nm
    , d.trade_quarter_nm
    , d.calendar_quarter_start_dt
    , d.trade_quarter_start_dt
    , d.calendar_quarter_start_key
    , d.trade_quarter_start_key
    , d.calendar_quarter_end_dt
    , d.trade_quarter_end_dt
    , d.calendar_quarter_end_key
    , d.trade_quarter_end_key
    , d.calendar_year_num
    , d.trade_year_num
    , d.calendar_year_start_dt
    , d.trade_year_start_dt
    , d.calendar_year_start_key
    , d.trade_year_start_key
    , d.calendar_year_end_dt
    , d.trade_year_end_dt
    , d.calendar_year_end_key
    , d.trade_year_end_key
    , d.calendar_leap_year_flg
    , d.trade_leap_week_flg
    , d.weeks_in_trade_year_num
    , d.iso_year_num
    , d.iso_week_of_year_txt
    , d.iso_week_overall_num
    , d.iso_week_start_dt
    , d.iso_week_start_key
    , d.iso_week_end_dt
    , d.iso_week_end_key
    , d.dw_synced_ts
    , d.dw_source_nm
    , d.create_user_id
    , d.create_timestamp
from
    bpruss_dw_util.dim_trade_date d;
