select
    date.date_key
    , date.full_dt
    , date.date_last_year_key
    , date.date_last_year_dt
    , date.day_of_week_num
    , date.iso_day_of_week_num
    , date.day_of_month_num
    , date.day_of_quarter_num
    , date.day_of_year_num
    , date.day_overall_num
    , date.day_nm
    , date.day_abbr
    , date.day_suffix_txt
    , date.epoch_num
    , date.weekday_flg
    , date.last_day_of_week_flg
    , date.first_day_of_month_flg
    , date.last_day_of_month_flg
    , date.last_day_of_quarter_flg
    , date.last_day_of_year_flg
    , date.week_num
    , date.week_of_year_num
    , date.week_of_month_num
    , date.week_of_quarter_num
    , date.week_overall_num
    , date.week_start_dt
    , date.week_start_key
    , date.week_end_dt
    , date.week_end_key
    , date.month_num
    , date.month_nm
    , date.month_abbr
    , date.month_in_quarter_num
    , date.month_overall_num
    , date.yearmonth_num
    , date.month_start_dt
    , date.month_start_key
    , date.month_end_dt
    , date.month_end_key
    , date.quarter_num
    , date.quarter_nm
    , date.quarter_full_nm
    , date.quarter_start_dt
    , date.quarter_start_key
    , date.quarter_end_dt
    , date.quarter_end_key
    , date.year_num
    , date.year_start_dt
    , date.year_start_key
    , date.year_end_dt
    , date.year_end_key
    , date.leap_year_flg
    , date.iso_year_num
    , date.iso_week_of_year_txt
    , date.iso_week_overall_num
    , date.iso_week_start_dt
    , date.iso_week_start_key
    , date.iso_week_end_dt
    , date.iso_week_end_key
    , date.dw_synced_ts
    , date.dw_source_nm
    , date.create_user_id
    , date.create_ts
from
    bpruss_dw_util.dim_date date;
