select
    d.date_key
    , d.full_dt
    , d.full_dt
    , d.trade_date_last_year_key
    , d.trade_day_of_year_num
    , d.trade_week_num
    , d.trade_week_of_year_num
    , d.trade_week_of_month_445_num
    , d.trade_week_of_month_454_num
    , d.trade_week_of_month_544_num
    , d.trade_week_of_quarter_num
    , d.trade_week_overall_num
    , d.trade_week_start_dt
    , d.trade_week_start_key
    , d.trade_week_end_dt
    , d.trade_week_end_key
    , d.trade_month_445_num
    , d.trade_month_454_num
    , d.trade_month_544_num
    , d.trade_month_445_nm
    , d.trade_month_454_nm
    , d.trade_month_544_nm
    , d.trade_month_abbr
    , d.trade_month_overall_num
    , d.trade_yearmonth_num
    , d.trade_month_445_start_dt
    , d.trade_month_454_start_dt
    , d.trade_month_544_start_dt
    , d.trade_month_445_start_key
    , d.trade_month_454_start_key
    , d.trade_month_544_start_key
    , d.trade_month_445_end_dt
    , d.trade_month_454_end_dt
    , d.trade_month_544_end_dt
    , d.trade_month_445_end_key
    , d.trade_month_454_end_key
    , d.trade_month_544_end_key
    , d.trade_quarter_num
    , d.trade_quarter_nm
    , d.trade_quarter_start_dt
    , d.trade_quarter_start_key
    , d.trade_quarter_end_dt
    , d.trade_quarter_end_key
    , d.trade_year_num
    , d.trade_year_start_dt
    , d.trade_year_start_key
    , d.trade_year_end_dt
    , d.trade_year_end_key
    , d.trade_leap_week_flg
    , d.weeks_in_trade_year_num
    , d.dw_synced_ts
    , d.dw_source_nm
    , d.create_user_id
    , d.create_timestamp
from
    bpruss_dw_util.dim_trade_date d;
